CREATE TABLE IF NOT EXISTS person_registry (
    person_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ho_ten TEXT NOT NULL,
    ma_nv TEXT,
    bo_phan TEXT,
    ngay_sinh DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS face_embeddings (
    person_id BIGINT PRIMARY KEY REFERENCES person_registry(person_id) ON DELETE CASCADE ON UPDATE CASCADE,
    emb REAL[] NOT NULL,
    emb_dim INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS camera_events (
    event_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT NOT NULL,
    event_ts TIMESTAMPTZ NOT NULL,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    weekday TEXT NOT NULL,
    cam_id TEXT NOT NULL,
    person_id BIGINT,
    person_name TEXT,
    people_count INTEGER,
    posture TEXT,
    holding BOOLEAN,
    track_id INTEGER,
    confidence REAL,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS camera_occupancy_samples (
    sample_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sample_ts TIMESTAMPTZ NOT NULL,
    cam_id TEXT NOT NULL,
    people_count INTEGER NOT NULL,
    unknown_count INTEGER NOT NULL DEFAULT 0,
    lying_count INTEGER NOT NULL DEFAULT 0,
    fall_count INTEGER NOT NULL DEFAULT 0,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_camera_events_ts ON camera_events(event_ts DESC);
CREATE INDEX IF NOT EXISTS idx_camera_events_type ON camera_events(event_type);
CREATE INDEX IF NOT EXISTS idx_camera_events_cam_id ON camera_events(cam_id);
CREATE INDEX IF NOT EXISTS idx_camera_samples_ts ON camera_occupancy_samples(sample_ts DESC);
CREATE INDEX IF NOT EXISTS idx_camera_samples_cam_id ON camera_occupancy_samples(cam_id);
