import os
from typing import Any, Dict, List, Optional

import numpy as np

import config

try:
    import psycopg2
    from psycopg2.extras import Json
except Exception:
    psycopg2 = None
    Json = None


SCHEMA_SQL = """
CREATE TABLE IF NOT EXISTS person_registry (
    person_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ho_ten TEXT NOT NULL,
    ma_nv TEXT,
    bo_phan TEXT,
    ngay_sinh DATE,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS face_embeddings (
    person_id BIGINT PRIMARY KEY REFERENCES person_registry(person_id) ON DELETE CASCADE ON UPDATE CASCADE,
    emb REAL[] NOT NULL,
    emb_dim INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS camera_events (
    event_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT NOT NULL,
    event_ts TIMESTAMPTZ NOT NULL,
    event_date DATE NOT NULL,
    event_time TIME NOT NULL,
    weekday TEXT NOT NULL,
    cam_id TEXT NOT NULL,
    person_id BIGINT,
    person_name TEXT,
    people_count INTEGER,
    posture TEXT,
    holding BOOLEAN,
    track_id INTEGER,
    confidence REAL,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS camera_occupancy_samples (
    sample_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sample_ts TIMESTAMPTZ NOT NULL,
    cam_id TEXT NOT NULL,
    people_count INTEGER NOT NULL,
    unknown_count INTEGER NOT NULL DEFAULT 0,
    lying_count INTEGER NOT NULL DEFAULT 0,
    fall_count INTEGER NOT NULL DEFAULT 0,
    extra JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_camera_events_ts ON camera_events(event_ts DESC);
CREATE INDEX IF NOT EXISTS idx_camera_events_type ON camera_events(event_type);
CREATE INDEX IF NOT EXISTS idx_camera_events_cam_id ON camera_events(cam_id);
CREATE INDEX IF NOT EXISTS idx_camera_samples_ts ON camera_occupancy_samples(sample_ts DESC);
CREATE INDEX IF NOT EXISTS idx_camera_samples_cam_id ON camera_occupancy_samples(cam_id);
"""


def _dsn_kwargs() -> Dict[str, Any]:
    database_url = (getattr(config, "DATABASE_URL", "") or "").strip()
    if database_url:
        return {"dsn": database_url}

    return {
        "host": config.PG_HOST,
        "port": config.PG_PORT,
        "dbname": config.PG_DATABASE,
        "user": config.PG_USER,
        "password": config.PG_PASSWORD,
        "connect_timeout": config.PG_CONNECT_TIMEOUT,
    }


def postgres_enabled() -> bool:
    return bool(getattr(config, "USE_POSTGRES", True))


def postgres_driver_ready() -> bool:
    return psycopg2 is not None


def get_connection():
    if not postgres_enabled() or not postgres_driver_ready():
        return None

    kwargs = _dsn_kwargs()
    try:
        if "dsn" in kwargs:
            conn = psycopg2.connect(kwargs["dsn"], connect_timeout=config.PG_CONNECT_TIMEOUT)
        else:
            conn = psycopg2.connect(**kwargs)
        conn.autocommit = True
        return conn
    except Exception as ex:
        print("[PG] Khong ket noi duoc PostgreSQL:", repr(ex))
        return None


def init_schema() -> bool:
    conn = get_connection()
    if conn is None:
        return False
    try:
        with conn.cursor() as cur:
            cur.execute(SCHEMA_SQL)
        print("[PG] Da khoi tao schema CV/PostgreSQL.")
        return True
    except Exception as ex:
        print("[PG] Loi tao schema:", repr(ex))
        return False
    finally:
        conn.close()


def count_people() -> Optional[int]:
    conn = get_connection()
    if conn is None:
        return None
    try:
        with conn.cursor() as cur:
            cur.execute("SELECT COUNT(*) FROM person_registry;")
            row = cur.fetchone()
            return int(row[0]) if row else 0
    except Exception as ex:
        print("[PG] Loi dem person_registry:", repr(ex))
        return None
    finally:
        conn.close()


def load_all_people() -> Optional[List[Dict[str, Any]]]:
    conn = get_connection()
    if conn is None:
        return None
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT p.person_id, p.ho_ten, p.ma_nv, p.bo_phan,
                       COALESCE(TO_CHAR(p.ngay_sinh, 'YYYY-MM-DD'), '') AS ngay_sinh,
                       e.emb
                FROM person_registry p
                LEFT JOIN face_embeddings e ON e.person_id = p.person_id
                WHERE p.is_active = TRUE
                ORDER BY p.person_id;
                """
            )
            rows = cur.fetchall()

        ds = []
        for row in rows:
            emb = row[5]
            emb_np = np.asarray(emb, dtype=np.float32) if emb else None
            ds.append({
                "person_id": int(row[0]),
                "ho_ten": row[1] or "",
                "ma_nv": row[2] or "",
                "bo_phan": row[3] or "",
                "ngay_sinh": row[4] or "",
                "emb_file": "",
                "embed": emb_np,
            })
        return ds
    except Exception as ex:
        print("[PG] Loi load person_registry:", repr(ex))
        return None
    finally:
        conn.close()


def _set_identity_sequence(cur) -> None:
    cur.execute(
        """
        SELECT setval(
            pg_get_serial_sequence('person_registry', 'person_id'),
            COALESCE((SELECT MAX(person_id) FROM person_registry), 1),
            TRUE
        );
        """
    )


def upsert_person(person_id, ho_ten, ma_nv, bo_phan, ngay_sinh, embed) -> Optional[int]:
    conn = get_connection()
    if conn is None:
        return None

    emb_list = None
    if embed is not None:
        emb_list = np.asarray(embed, dtype=np.float32).tolist()

    ngay_sinh_value = ngay_sinh.strip() if isinstance(ngay_sinh, str) else ngay_sinh
    if ngay_sinh_value == "":
        ngay_sinh_value = None

    try:
        with conn.cursor() as cur:
            if person_id is None or str(person_id).strip() == "":
                cur.execute(
                    """
                    INSERT INTO person_registry (ho_ten, ma_nv, bo_phan, ngay_sinh)
                    VALUES (%s, %s, %s, %s)
                    RETURNING person_id;
                    """,
                    (ho_ten, ma_nv, bo_phan, ngay_sinh_value)
                )
                new_id = int(cur.fetchone()[0])
            else:
                new_id = int(person_id)
                cur.execute("SELECT 1 FROM person_registry WHERE person_id = %s;", (new_id,))
                if cur.fetchone() is not None:
                    print(f"[PG] person_id={new_id} da ton tai.")
                    return None

                cur.execute(
                    """
                    INSERT INTO person_registry (person_id, ho_ten, ma_nv, bo_phan, ngay_sinh)
                    VALUES (%s, %s, %s, %s, %s);
                    """,
                    (new_id, ho_ten, ma_nv, bo_phan, ngay_sinh_value)
                )
                _set_identity_sequence(cur)

            if emb_list is not None:
                cur.execute(
                    """
                    INSERT INTO face_embeddings (person_id, emb, emb_dim)
                    VALUES (%s, %s, %s)
                    ON CONFLICT (person_id)
                    DO UPDATE SET emb = EXCLUDED.emb,
                                  emb_dim = EXCLUDED.emb_dim,
                                  updated_at = NOW();
                    """,
                    (new_id, emb_list, len(emb_list))
                )

        return int(new_id)
    except Exception as ex:
        print("[PG] Loi them nhan su:", repr(ex))
        return None
    finally:
        conn.close()


def update_person(existing_person_id: int, new_person_id=None, ho_ten=None, ma_nv=None, bo_phan=None, ngay_sinh=None) -> bool:
    conn = get_connection()
    if conn is None:
        return False

    ngay_sinh_value = ngay_sinh.strip() if isinstance(ngay_sinh, str) else ngay_sinh
    if ngay_sinh_value == "":
        ngay_sinh_value = None

    try:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT person_id, ho_ten, ma_nv, bo_phan, COALESCE(TO_CHAR(ngay_sinh, 'YYYY-MM-DD'), '') FROM person_registry WHERE person_id = %s;",
                (int(existing_person_id),)
            )
            row = cur.fetchone()
            if row is None:
                print(f"[PG] Khong tim thay person_id={existing_person_id}")
                return False

            final_person_id = int(new_person_id) if str(new_person_id).strip() else int(existing_person_id)
            if final_person_id != int(existing_person_id):
                cur.execute("SELECT 1 FROM person_registry WHERE person_id = %s;", (final_person_id,))
                if cur.fetchone() is not None:
                    print(f"[PG] person_id={final_person_id} da ton tai.")
                    return False

            cur.execute(
                """
                UPDATE person_registry
                SET person_id = %s,
                    ho_ten = %s,
                    ma_nv = %s,
                    bo_phan = %s,
                    ngay_sinh = %s,
                    updated_at = NOW()
                WHERE person_id = %s;
                """,
                (
                    final_person_id,
                    ho_ten if ho_ten is not None and ho_ten != "" else row[1],
                    ma_nv if ma_nv is not None and ma_nv != "" else row[2],
                    bo_phan if bo_phan is not None and bo_phan != "" else row[3],
                    ngay_sinh_value if ngay_sinh is not None and ngay_sinh != "" else (row[4] or None),
                    int(existing_person_id),
                )
            )
            _set_identity_sequence(cur)
        return True
    except Exception as ex:
        print("[PG] Loi sua thong tin nhan su:", repr(ex))
        return False
    finally:
        conn.close()


def delete_person(person_id: int) -> bool:
    conn = get_connection()
    if conn is None:
        return False
    try:
        with conn.cursor() as cur:
            cur.execute("DELETE FROM person_registry WHERE person_id = %s;", (int(person_id),))
            if cur.rowcount <= 0:
                print(f"[PG] Khong tim thay person_id={person_id}")
                return False
        return True
    except Exception as ex:
        print("[PG] Loi xoa person:", repr(ex))
        return False
    finally:
        conn.close()


def migrate_csv_people(csv_people: List[Dict[str, Any]]) -> bool:
    if not csv_people:
        return True
    conn = get_connection()
    if conn is None:
        return False
    try:
        with conn.cursor() as cur:
            for person in csv_people:
                person_id = int(person["person_id"])
                ho_ten = person.get("ho_ten", "")
                ma_nv = person.get("ma_nv", "")
                bo_phan = person.get("bo_phan", "")
                ngay_sinh = person.get("ngay_sinh", "") or None
                emb = person.get("embed")
                emb_list = np.asarray(emb, dtype=np.float32).tolist() if emb is not None else None

                cur.execute(
                    """
                    INSERT INTO person_registry (person_id, ho_ten, ma_nv, bo_phan, ngay_sinh)
                    VALUES (%s, %s, %s, %s, %s)
                    ON CONFLICT (person_id)
                    DO UPDATE SET ho_ten = EXCLUDED.ho_ten,
                                  ma_nv = EXCLUDED.ma_nv,
                                  bo_phan = EXCLUDED.bo_phan,
                                  ngay_sinh = EXCLUDED.ngay_sinh,
                                  updated_at = NOW();
                    """,
                    (person_id, ho_ten, ma_nv, bo_phan, ngay_sinh)
                )

                if emb_list is not None:
                    cur.execute(
                        """
                        INSERT INTO face_embeddings (person_id, emb, emb_dim)
                        VALUES (%s, %s, %s)
                        ON CONFLICT (person_id)
                        DO UPDATE SET emb = EXCLUDED.emb,
                                      emb_dim = EXCLUDED.emb_dim,
                                      updated_at = NOW();
                        """,
                        (person_id, emb_list, len(emb_list))
                    )
            _set_identity_sequence(cur)
        print(f"[PG] Da migrate {len(csv_people)} nhan su tu CSV len PostgreSQL.")
        return True
    except Exception as ex:
        print("[PG] Loi migrate CSV -> PostgreSQL:", repr(ex))
        return False
    finally:
        conn.close()


__all__ = [
    "Json",
    "count_people",
    "delete_person",
    "get_connection",
    "init_schema",
    "load_all_people",
    "migrate_csv_people",
    "postgres_driver_ready",
    "postgres_enabled",
    "upsert_person",
    "update_person",
]
